# Generated by Django 3.0.7 on 2020-06-07 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='sub_hours',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(744)]),
        ),
    ]
